#!/usr/bin/env python3
"""Hive OS PXE deploy server: admin UI, rig-facing HTTP endpoints, dnsmasq supervisor.

Stdlib only. Two listeners:
  ADMIN_PORT  (8381) admin UI, session login, forced password change (behind Umbrel app_proxy on 8380)
  PUBLIC_PORT (8382) unauthenticated, LAN-facing: iPXE script, netboot files, image, per-rig config
"""
import hashlib, hmac, html, io, json, os, re, secrets, shutil, socket, subprocess, tarfile
import threading, time, urllib.request, tempfile
from collections import deque
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from http.cookies import SimpleCookie
from urllib.parse import urlparse, parse_qs, quote

DATA = os.environ.get("DATA_DIR", "/data")
TFTP = os.environ.get("TFTP_DIR", "/srv/tftp")
NETBOOT = os.environ.get("NETBOOT_DIR", "/srv/netboot")
ADMIN_PORT = int(os.environ.get("ADMIN_PORT", "8381"))
PUBLIC_PORT = int(os.environ.get("PUBLIC_PORT", "8382"))
ALPINE_BRANCH = os.environ.get("ALPINE_BRANCH", "v3.20")
DNSMASQ_BIN = os.environ.get("DNSMASQ_BIN", "dnsmasq")
IMAGES = os.path.join(DATA, "images")
CFG_PATH = os.path.join(DATA, "config.json")
MAC_RE = re.compile(r"^([0-9a-f]{2}:){5}[0-9a-f]{2}$")

lock = threading.RLock()
log_lines = deque(maxlen=200)      # dnsmasq output
events = deque(maxlen=100)         # rig-side reports
fetches = {}                       # image download progress
sessions = {}                      # sid -> csrf
dnsmasq_proc = None


# ---------- config ----------
def now(): return time.strftime("%Y-%m-%d %H:%M:%S")

def hash_pw(pw, salt=None):
    salt = salt or secrets.token_hex(16)
    h = hashlib.scrypt(pw.encode(), salt=salt.encode(), n=2**14, r=8, p=1).hex()
    return f"{salt}${h}"

def check_pw(pw, stored):
    salt, _ = stored.split("$", 1)
    return hmac.compare_digest(hash_pw(pw, salt), stored)

def default_cfg():
    initial = os.environ.get("INITIAL_PASSWORD") or secrets.token_urlsafe(9)
    if not os.environ.get("INITIAL_PASSWORD"):
        print(f"*** initial admin password: {initial}", flush=True)
    return {
        "password": hash_pw(initial), "password_changed": False,
        "server_ip": "", "image": "",
        "groups": {"default": {"network": "192.168.1.0/24", "gateway": "192.168.1.1", "dns": "",
                               "hive_url": "https://api2.hiveos.farm", "farm_hash": "", "disk": ""}},
        "rigs": {},
    }

def load():
    os.makedirs(IMAGES, exist_ok=True)
    if os.path.exists(CFG_PATH):
        with open(CFG_PATH) as f: return json.load(f)
    c = default_cfg(); save(c); return c

def save(c):
    with lock:
        tmp = CFG_PATH + ".tmp"
        with open(tmp, "w") as f: json.dump(c, f, indent=1)
        os.replace(tmp, CFG_PATH)

cfg = None

def norm_mac(m):
    m = re.sub(r"[^0-9a-fA-F]", "", m or "").lower()
    return ":".join(m[i:i+2] for i in range(0, 12, 2)) if len(m) == 12 else ""


# ---------- network detection ----------
def detect_net():
    """Return (ip, iface) of the default-route interface."""
    ip = iface = ""
    try:
        out = subprocess.run(["ip", "-4", "route", "get", "1.1.1.1"], capture_output=True, text=True, timeout=5).stdout
        m = re.search(r"dev (\S+)", out); iface = m.group(1) if m else ""
        m = re.search(r"src (\S+)", out); ip = m.group(1) if m else ""
    except Exception: pass
    if not ip:
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.connect(("1.1.1.1", 53))
            ip = s.getsockname()[0]; s.close()
        except Exception: ip = "127.0.0.1"
    return ip, iface

def server_ip():
    return cfg.get("server_ip") or os.environ.get("SERVER_IP") or detect_net()[0]


# ---------- dnsmasq ----------
def write_dnsmasq():
    ip, iface = detect_net()
    ip = cfg.get("server_ip") or os.environ.get("SERVER_IP") or ip
    conf = f"""# generated by server.py -- do not edit
port=0
{f'interface={iface}' if iface else ''}
bind-interfaces
log-dhcp
dhcp-range={ip},proxy
enable-tftp
tftp-root={TFTP}
dhcp-match=set:ipxe,175
pxe-service=tag:!ipxe,x86PC,"Hive OS Deploy (BIOS)",undionly.kpxe
pxe-service=tag:!ipxe,BC_EFI,"Hive OS Deploy (UEFI)",ipxe.efi
pxe-service=tag:!ipxe,X86-64_EFI,"Hive OS Deploy (UEFI)",ipxe.efi
pxe-service=tag:ipxe,x86PC,"Hive OS Deploy",boot.ipxe
pxe-service=tag:ipxe,BC_EFI,"Hive OS Deploy",boot.ipxe
pxe-service=tag:ipxe,X86-64_EFI,"Hive OS Deploy",boot.ipxe
"""
    os.makedirs(TFTP, exist_ok=True)
    with open(os.path.join(TFTP, "boot.ipxe"), "w") as f:  # tiny stub: hand over to the dynamic HTTP script
        f.write(f"#!ipxe\nchain http://{ip}:{PUBLIC_PORT}/boot.ipxe?mac=${{net0/mac}} || exit\n")
    path = os.path.join(tempfile.gettempdir(), "dnsmasq.conf")
    with open(path, "w") as f: f.write(conf)
    return path

def run_dnsmasq():
    global dnsmasq_proc
    with lock:
        if dnsmasq_proc and dnsmasq_proc.poll() is None:
            dnsmasq_proc.terminate(); dnsmasq_proc.wait(5)
        path = write_dnsmasq()
        try:
            dnsmasq_proc = subprocess.Popen([DNSMASQ_BIN, "--keep-in-foreground", "--log-facility=-", f"--conf-file={path}"],
                                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        except FileNotFoundError:
            log_lines.append(f"{now()} dnsmasq binary not found"); return
    threading.Thread(target=pump, args=(dnsmasq_proc,), daemon=True).start()

def pump(p):
    for line in p.stdout:
        line = line.rstrip(); log_lines.append(line); print(line, flush=True)

def supervise():
    while True:
        time.sleep(10)
        if dnsmasq_proc is not None and dnsmasq_proc.poll() is not None:
            log_lines.append(f"{now()} dnsmasq exited ({dnsmasq_proc.returncode}), restarting"); run_dnsmasq()


# ---------- rig-facing content ----------
def build_apkovl():
    """Alpine overlay that runs flash.sh at boot. Built once per start."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as t:
        def add(name, data, mode=0o644):
            ti = tarfile.TarInfo(name); ti.size = len(data); ti.mode = mode; ti.mtime = int(time.time())
            t.addfile(ti, io.BytesIO(data))
        def link(name, target):
            ti = tarfile.TarInfo(name); ti.type = tarfile.SYMTYPE; ti.linkname = target; t.addfile(ti)
        with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "scripts", "flash.sh"), "rb") as f:
            add("etc/local.d/hive-flash.start", f.read(), 0o755)
        add("etc/network/interfaces", b"auto lo\niface lo inet loopback\nauto eth0\niface eth0 inet dhcp\n")
        add("etc/apk/world", b"alpine-base\n")
        link("etc/runlevels/boot/networking", "/etc/init.d/networking")
        link("etc/runlevels/default/local", "/etc/init.d/local")
    return buf.getvalue()

def boot_script(mac):
    ip, srv = server_ip(), f"http://{server_ip()}:{PUBLIC_PORT}"
    rig = cfg["rigs"].get(mac)
    if not rig or not cfg["image"] or rig.get("state") in ("done", "skip"):
        why = "unknown rig" if not rig else "no image selected" if not cfg["image"] else "already deployed"
        return f"#!ipxe\necho Hive deploy: {why}, booting local disk\nsanboot --no-describe --drive 0x80 || exit\n"
    return (f"#!ipxe\necho Hive deploy: flashing {rig['name']} ({mac})\n"
            f"kernel {srv}/netboot/vmlinuz-lts ip=dhcp console=tty0 modules=loop,squashfs,vfat "
            f"alpine_repo=http://dl-cdn.alpinelinux.org/alpine/{ALPINE_BRANCH}/main "
            f"modloop={srv}/netboot/modloop-lts apkovl={srv}/hive.apkovl.tar.gz hive_server={srv} hive_mac={mac}\n"
            f"initrd {srv}/netboot/initramfs-lts\nboot\n")

def group_of(rig): return cfg["groups"].get(rig.get("group"), next(iter(cfg["groups"].values())))

def rig_conf(rig):
    g = group_of(rig)
    lines = [f'HIVE_HOST_URL="{g["hive_url"]}"', f'FARM_HASH={g["farm_hash"]}', f'WORKER_NAME="{rig["name"]}"']
    return "\n".join(lines) + "\n"

def network_file(rig):
    """systemd-networkd config for /hive-config/network/20-ethernet.network, only if the rig has a static IP."""
    if not rig.get("ip"): return None
    g = group_of(rig)
    prefix = g["network"].split("/")[1] if "/" in g["network"] else "24"
    dns = g.get("dns") or g["gateway"]
    return f"[Match]\nName=e*\n\n[Network]\nDHCP=no\nAddress={rig['ip']}/{prefix}\nGateway={g['gateway']}\nDNS={dns}\n"

def flash_env(rig):
    g = group_of(rig)
    return f'IMAGE="{cfg["image"]}"\nTARGET_DISK="{g.get("disk", "")}"\n'


# ---------- HTML helpers ----------
CSS = """:root{color-scheme:light dark;--bg:#fff;--fg:#1a1a1a;--mut:#666;--bd:#ddd;--ac:#2563eb;--ok:#15803d;--bad:#b91c1c}
@media(prefers-color-scheme:dark){:root{--bg:#141414;--fg:#e8e8e8;--mut:#999;--bd:#333;--ac:#60a5fa;--ok:#4ade80;--bad:#f87171}}
body{font:15px system-ui,sans-serif;background:var(--bg);color:var(--fg);margin:0}main{max-width:960px;margin:0 auto;padding:16px}
nav a{margin-right:14px;color:var(--ac);text-decoration:none}h1{font-size:20px}h2{font-size:16px;margin-top:28px}
table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid var(--bd);padding:6px 8px;text-align:left;font-size:14px}
input,select,button,textarea{font:inherit;padding:6px 8px;background:transparent;color:inherit;border:1px solid var(--bd);border-radius:6px;max-width:100%}
button{cursor:pointer;background:var(--ac);color:#fff;border-color:var(--ac)}button.g{background:transparent;color:var(--fg);border-color:var(--bd)}
.ok{color:var(--ok)}.bad{color:var(--bad)}.mut{color:var(--mut)}pre{background:#0002;padding:8px;border-radius:6px;overflow:auto;max-height:260px;font-size:12px}
form.row{display:flex;flex-wrap:wrap;gap:8px;align-items:end;margin:8px 0}form.row label{display:flex;flex-direction:column;font-size:12px;color:var(--mut);gap:2px}
form.inl{display:inline}.card{border:1px solid var(--bd);border-radius:8px;padding:8px 12px;margin:8px 0}"""

def e(s): return html.escape(str(s), quote=True)

def page(title, body, sid=None):
    nav = ""
    if sid:
        nav = ('<nav><a href="/">Status</a><a href="/rigs">Rigs</a><a href="/groups">Groups</a><a href="/images">Image</a>'
               '<a href="/settings">Settings</a><a href="/password">Password</a>'
               f'<form class="inl" method="post" action="/logout"><input type="hidden" name="csrf" value="{sessions[sid]}">'
               '<button class="g">Log out</button></form></nav>')
    return (f'<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1">'
            f'<title>{e(title)} - Hive PXE Deploy</title><style>{CSS}</style><main>{nav}<h1>{e(title)}</h1>{body}</main>').encode()

def csrf(sid): return f'<input type="hidden" name="csrf" value="{sessions[sid]}">'


# ---------- admin pages ----------
def p_status(sid, q):
    ip, iface = detect_net(); ip = server_ip()
    up = dnsmasq_proc is not None and dnsmasq_proc.poll() is None
    rows = "".join(
        f'<tr><td>{e(r["name"])}</td><td>{e(m)}</td><td>{e(r.get("ip") or "-")}</td>'
        f'<td class="{"ok" if r.get("state")=="done" else "bad" if r.get("state")=="failed" else ""}">{e(r.get("state","pending"))}</td>'
        f'<td class="mut">{e(r.get("seen","-"))}</td></tr>' for m, r in cfg["rigs"].items())
    img = e(cfg["image"]) if cfg["image"] else '<span class="bad">none selected</span>'
    ev = "\n".join(list(events)[-15:][::-1]) or "no reports yet"
    lg = "\n".join(list(log_lines)[-40:][::-1]) or "no dnsmasq output yet"
    return page("Status", f"""<div class=card>Server IP <b>{e(ip)}</b> on <b>{e(iface or '?')}</b> &middot; proxy-DHCP/TFTP (dnsmasq):
<b class="{'ok' if up else 'bad'}">{'running' if up else 'stopped'}</b> &middot; image: <b>{img}</b> &middot; rig files: <code>http://{e(ip)}:{PUBLIC_PORT}</code></div>
<p class=mut>Reminder: give this machine a static IP or DHCP reservation, or rigs will PXE to a stale address.</p>
<h2>Rigs</h2><table><tr><th>Name<th>MAC<th>IP<th>State<th>Last seen</tr>{rows or '<tr><td colspan=5 class=mut>No rigs yet</tr>'}</table>
<h2>Rig reports</h2><pre>{e(ev)}</pre><h2>dnsmasq log (newest first)</h2><pre>{e(lg)}</pre>""", sid)

def p_rigs(sid, q):
    gopts = "".join(f'<option>{e(g)}</option>' for g in cfg["groups"])
    rows = ""
    for m, r in cfg["rigs"].items():
        c = csrf(sid); mm = quote(m)
        rows += (f'<tr><td>{e(r["name"])}<td>{e(m)}<td>{e(r.get("ip") or "-")}<td>{e(r.get("group"))}<td>{e(r.get("state","pending"))}'
                 f'<td><form class=inl method=post action="/rigs/{mm}/reflash">{c}<button class=g>Reflash</button></form> '
                 f'<form class=inl method=post action="/rigs/{mm}/skip">{c}<button class=g>Mark done</button></form> '
                 f'<form class=inl method=post action="/rigs/{mm}/delete">{c}<button class=g>Delete</button></form></tr>')
    return page("Rigs", f"""<table><tr><th>Name<th>MAC<th>IP<th>Group<th>State<th></tr>{rows or '<tr><td colspan=6 class=mut>None</tr>'}</table>
<h2>Add rig</h2><form class=row method=post action=/rigs/add>{csrf(sid)}
<label>Name<input name=name required></label><label>MAC<input name=mac required placeholder="aa:bb:cc:dd:ee:ff"></label>
<label>IP (optional)<input name=ip placeholder="192.168.1.51"></label><label>Group<select name=group>{gopts}</select></label><button>Add</button></form>
<h2>Import list</h2><p class=mut>One rig per line: <code>name MAC [IP] [group]</code> (space, comma or tab separated)</p>
<form method=post action=/rigs/import>{csrf(sid)}<textarea name=list rows=6 style="width:100%"></textarea><br><button>Import</button></form>
<p class=mut>A rig is flashed on its next PXE boot until it reports success; after that it boots from its own disk. "Reflash" re-arms it.</p>""", sid)

def p_groups(sid, q):
    cards = ""
    for n, g in cfg["groups"].items():
        cards += f"""<div class=card><form class=row method=post action=/groups/save>{csrf(sid)}<input type=hidden name=name value="{e(n)}">
<b>{e(n)}</b><label>Network (CIDR)<input name=network value="{e(g['network'])}"></label><label>Gateway<input name=gateway value="{e(g['gateway'])}"></label>
<label>DNS (blank = gateway)<input name=dns value="{e(g.get('dns',''))}"></label><label>Hive API URL<input name=hive_url value="{e(g['hive_url'])}" size=28></label>
<label>Farm hash<input name=farm_hash value="{e(g['farm_hash'])}"></label><label>Target disk (blank = auto)<input name=disk value="{e(g.get('disk',''))}" placeholder=/dev/sda></label>
<button>Save</button></form>
<form method=post action="/groups/{quote(n)}/delete">{csrf(sid)}<button class=g>Delete group</button></form></div>"""
    return page("Groups", cards + f"""<h2>New group</h2><form class=row method=post action=/groups/save>{csrf(sid)}
<label>Name<input name=name required></label><label>Network<input name=network value="192.168.1.0/24"></label><label>Gateway<input name=gateway value="192.168.1.1"></label>
<label>Hive API URL<input name=hive_url value="https://api2.hiveos.farm"></label><label>Farm hash<input name=farm_hash></label><button>Create</button></form>
<p class=mut>Network/gateway/DNS only apply to rigs with a fixed IP. Rigs without one keep using DHCP from your router.</p>""", sid)

def p_images(sid, q):
    files = sorted(f for f in os.listdir(IMAGES) if not f.endswith(".part"))
    rows = ""
    for f in files:
        sz = os.path.getsize(os.path.join(IMAGES, f)) / 1e6
        sel = "<b class=ok>active</b>" if f == cfg["image"] else ""
        rows += (f'<tr><td>{e(f)}<td>{sz:,.0f} MB<td>{sel}<td><form class=inl method=post action=/images/select>{csrf(sid)}<input type=hidden name=file value="{e(f)}"><button class=g>Use</button></form> '
                 f'<form class=inl method=post action=/images/delete>{csrf(sid)}<input type=hidden name=file value="{e(f)}"><button class=g>Delete</button></form></tr>')
    prog = "".join(f'<div class=card>{e(k)}: {e(v)}</div>' for k, v in fetches.items())
    return page("Image", f"""{prog}<table><tr><th>File<th>Size<th><th></tr>{rows or '<tr><td colspan=4 class=mut>No images</tr>'}</table>
<h2>Download image from URL</h2><form class=row method=post action=/images/fetch>{csrf(sid)}
<label>URL of a Hive OS .img.xz / .img.gz / .img<input name=url size=60 required></label><button>Download</button></form>
<p class=mut>Or copy the file into <code>&lt;umbrel&gt;/app-data/HiveOSPXE-hive-os-pxe/data/images/</code>. Get the link from hiveos.farm downloads.</p>""", sid)

def p_settings(sid, q):
    ip, _ = detect_net()
    return page("Settings", f"""<form class=row method=post action=/settings>{csrf(sid)}
<label>Server IP override (blank = auto: {e(ip)})<input name=server_ip value="{e(cfg.get('server_ip',''))}"></label><button>Save &amp; restart dnsmasq</button></form>""", sid)

def p_password(sid, q, msg=""):
    forced = not cfg["password_changed"]
    return page("Change password", (f'<p class=bad>You must set a new password before continuing.</p>' if forced else "") + msg +
                f"""<form class=row method=post action=/password>{csrf(sid)}<label>Current<input type=password name=old required></label>
<label>New (min 8)<input type=password name=new required minlength=8></label><label>Repeat<input type=password name=new2 required></label><button>Change</button></form>""", sid)

def fetch_image(url):
    name = os.path.basename(urlparse(url).path) or "hiveos.img"
    name = re.sub(r"[^A-Za-z0-9._-]", "_", name)
    dst = os.path.join(IMAGES, name)
    try:
        fetches[name] = "starting"
        with urllib.request.urlopen(url, timeout=30) as r, open(dst + ".part", "wb") as f:
            total = int(r.headers.get("Content-Length", 0)); done = 0
            while chunk := r.read(1 << 20):
                f.write(chunk); done += len(chunk)
                fetches[name] = f"{done/1e6:,.0f} / {total/1e6:,.0f} MB" if total else f"{done/1e6:,.0f} MB"
        os.replace(dst + ".part", dst)
        fetches[name] = "done"
        if not cfg["image"]:
            cfg["image"] = name; save(cfg)
    except Exception as ex:
        fetches[name] = f"failed: {ex}"


# ---------- handlers ----------
class Base(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    def log_message(self, fmt, *a): pass

    def send(self, code, body=b"", ctype="text/html; charset=utf-8", headers=None):
        self.send_response(code); self.send_header("Content-Type", ctype); self.send_header("Content-Length", str(len(body)))
        for k, v in (headers or {}).items(): self.send_header(k, v)
        self.end_headers()
        if self.command != "HEAD": self.wfile.write(body)

    def redirect(self, to, headers=None): self.send(303, b"", headers={"Location": to, **(headers or {})})

    def stream_file(self, path, ctype="application/octet-stream"):
        if not os.path.isfile(path): return self.send(404, b"not found", "text/plain")
        size = os.path.getsize(path)
        self.send_response(200); self.send_header("Content-Type", ctype); self.send_header("Content-Length", str(size)); self.end_headers()
        if self.command == "HEAD": return
        with open(path, "rb") as f: shutil.copyfileobj(f, self.wfile, 1 << 20)


class Public(Base):
    def do_HEAD(self): self.do_GET()
    def do_GET(self):
        u = urlparse(self.path); q = parse_qs(u.query); p = u.path
        if p == "/boot.ipxe":
            mac = norm_mac(q.get("mac", [""])[0])
            with lock:
                if mac in cfg["rigs"]:
                    cfg["rigs"][mac]["seen"] = now(); save(cfg)
                events.append(f"{now()} boot.ipxe requested by {mac or 'unknown'}")
                return self.send(200, boot_script(mac).encode(), "text/plain")
        if p == "/hive.apkovl.tar.gz": return self.send(200, build_apkovl(), "application/gzip")
        if p.startswith("/netboot/"): return self.stream_file(os.path.join(NETBOOT, os.path.basename(p)))
        if p.startswith("/image/"):
            return self.stream_file(os.path.join(IMAGES, os.path.basename(p)))
        if p == "/api/ping": return self.send(200, b"ok", "text/plain")
        m = re.match(r"^/api/config/([^/]+)/(flash\.env|rig\.conf|20-ethernet\.network)$", p)
        if m:
            mac = norm_mac(m.group(1)); rig = cfg["rigs"].get(mac)
            if not rig: return self.send(404, b"unknown rig", "text/plain")
            body = {"flash.env": flash_env, "rig.conf": rig_conf, "20-ethernet.network": network_file}[m.group(2)](rig)
            return self.send(200, body.encode(), "text/plain") if body else self.send(404, b"none", "text/plain")
        if p == "/api/report":
            mac = norm_mac(q.get("mac", [""])[0]); st = q.get("status", [""])[0]; msg = q.get("msg", [""])[0].replace("_", " ")
            with lock:
                rig = cfg["rigs"].get(mac)
                if rig and st in ("start", "done", "failed"):
                    rig["state"] = {"start": "flashing", "done": "done", "failed": "failed"}[st]; rig["seen"] = now(); save(cfg)
                events.append(f"{now()} {rig['name'] if rig else mac}: {st} {msg[:200]}")
            return self.send(200, b"ok", "text/plain")
        self.send(404, b"not found", "text/plain")


class Admin(Base):
    def session(self):
        c = SimpleCookie(self.headers.get("Cookie", ""))
        sid = c["sid"].value if "sid" in c else None
        return sid if sid in sessions else None

    def form(self):
        n = int(self.headers.get("Content-Length", 0))
        return {k: v[0] for k, v in parse_qs(self.rfile.read(n).decode()).items()}

    def do_GET(self):
        u = urlparse(self.path); q = parse_qs(u.query); p = u.path
        if p == "/login": return self.send(200, self.login_page())
        sid = self.session()
        if not sid: return self.redirect("/login")
        if not cfg["password_changed"] and p != "/password": return self.redirect("/password")
        routes = {"/": p_status, "/rigs": p_rigs, "/groups": p_groups, "/images": p_images, "/settings": p_settings, "/password": p_password}
        if p == "/api/status":
            return self.send(200, json.dumps({"dnsmasq": bool(dnsmasq_proc and dnsmasq_proc.poll() is None), "rigs": cfg["rigs"], "image": cfg["image"]}).encode(), "application/json")
        if p in routes: return self.send(200, routes[p](sid, q))
        self.send(404, page("Not found", "", sid))

    def login_page(self, msg=""):
        return (f'<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Login</title><style>{CSS}</style><main><h1>Hive PXE Deploy</h1>{msg}'
                '<form class=row method=post action=/login><label>Password<input type=password name=pw autofocus></label><button>Log in</button></form></main>').encode()

    def do_POST(self):
        p = urlparse(self.path).path; f = self.form()
        if p == "/login":
            if check_pw(f.get("pw", ""), cfg["password"]):
                sid = secrets.token_urlsafe(24); sessions[sid] = secrets.token_urlsafe(16)
                return self.redirect("/", {"Set-Cookie": f"sid={sid}; HttpOnly; SameSite=Strict; Path=/"})
            time.sleep(1); return self.send(401, self.login_page('<p class=bad>Wrong password</p>'))
        sid = self.session()
        if not sid or not hmac.compare_digest(f.get("csrf", ""), sessions[sid]): return self.redirect("/login")
        if p == "/logout": sessions.pop(sid, None); return self.redirect("/login")
        if p == "/password":
            if not check_pw(f.get("old", ""), cfg["password"]): return self.send(200, p_password(sid, {}, '<p class=bad>Current password is wrong</p>'))
            if len(f.get("new", "")) < 8 or f["new"] != f.get("new2") or f["new"] == f["old"]:
                return self.send(200, p_password(sid, {}, '<p class=bad>New password must be 8+ chars, match, and differ from the old one</p>'))
            cfg["password"] = hash_pw(f["new"]); cfg["password_changed"] = True; save(cfg)
            for s in [s for s in sessions if s != sid]: sessions.pop(s)
            return self.redirect("/")
        if not cfg["password_changed"]: return self.redirect("/password")
        with lock:
            if p == "/rigs/add" or p == "/rigs/import":
                items = [(f.get("name"), f.get("mac"), f.get("ip"), f.get("group"))] if p == "/rigs/add" else \
                        [tuple((re.split(r"[\s,;]+", l.strip()) + ["", "", ""])[:4]) for l in f.get("list", "").splitlines() if l.strip()]
                for n, m, ip, g in items:
                    m = norm_mac(m)
                    if p == "/rigs/import" and not MAC_RE.match(ip or "x") and ip and re.match(r"^\d+\.\d+\.\d+\.\d+$", ip) is None: g, ip = ip, ""
                    if m and n: cfg["rigs"][m] = {"name": re.sub(r"[^A-Za-z0-9._-]", "", n), "ip": ip or "", "group": g if g in cfg["groups"] else "default", "state": "pending"}
                save(cfg); return self.redirect("/rigs")
            m = re.match(r"^/rigs/([^/]+)/(delete|reflash|skip)$", p)
            if m:
                mac = norm_mac(m.group(1).replace("%3A", ":")) or m.group(1); r = cfg["rigs"].get(mac)
                if r:
                    if m.group(2) == "delete": cfg["rigs"].pop(mac)
                    else: r["state"] = "pending" if m.group(2) == "reflash" else "done"
                    save(cfg)
                return self.redirect("/rigs")
            if p == "/groups/save":
                n = re.sub(r"[^A-Za-z0-9._-]", "", f.get("name", ""))
                if n:
                    g = cfg["groups"].setdefault(n, {})
                    for k in ("network", "gateway", "dns", "hive_url", "farm_hash", "disk"): g[k] = f.get(k, g.get(k, "")).strip()
                    save(cfg)
                return self.redirect("/groups")
            m = re.match(r"^/groups/([^/]+)/delete$", p)
            if m:
                if len(cfg["groups"]) > 1 and m.group(1) in cfg["groups"]:
                    cfg["groups"].pop(m.group(1))
                    for r in cfg["rigs"].values():
                        if r["group"] not in cfg["groups"]: r["group"] = next(iter(cfg["groups"]))
                    save(cfg)
                return self.redirect("/groups")
            if p == "/images/select":
                if os.path.isfile(os.path.join(IMAGES, os.path.basename(f.get("file", "")))): cfg["image"] = os.path.basename(f["file"]); save(cfg)
                return self.redirect("/images")
            if p == "/images/delete":
                fn = os.path.basename(f.get("file", "")); fp = os.path.join(IMAGES, fn)
                if os.path.isfile(fp): os.remove(fp)
                if cfg["image"] == fn: cfg["image"] = ""; save(cfg)
                return self.redirect("/images")
            if p == "/images/fetch":
                if re.match(r"^https?://", f.get("url", "")): threading.Thread(target=fetch_image, args=(f["url"],), daemon=True).start()
                return self.redirect("/images")
            if p == "/settings":
                v = f.get("server_ip", "").strip()
                if v and not re.match(r"^\d+\.\d+\.\d+\.\d+$", v): return self.redirect("/settings")
                cfg["server_ip"] = v; save(cfg); run_dnsmasq(); return self.redirect("/")
        self.send(404, b"not found", "text/plain")


def serve(handler, port):
    ThreadingHTTPServer(("0.0.0.0", port), handler).serve_forever()

def main():
    global cfg
    cfg = load()
    threading.Thread(target=serve, args=(Public, PUBLIC_PORT), daemon=True).start()
    run_dnsmasq()
    threading.Thread(target=supervise, daemon=True).start()
    print(f"admin :{ADMIN_PORT}  public :{PUBLIC_PORT}  server ip {server_ip()}", flush=True)
    serve(Admin, ADMIN_PORT)

if __name__ == "__main__":
    main()
